version: "3.8"
services:
  cytex-texlive:
    # ubuntu 18.04
    # image: ran350/cytex-texlive:0.0.1
    # ubuntu 24.04
    image: tamagoham/cytex-texlive:0.0.1
    # build: . # if you want to build the image locally
    volumes:
      - ../:/workspaces/CyTeX
      - ./.latexmkrc:/root/.latexmkrc
    tty: true
    environment:
      SHELL: "/bin/bash"
